Traceback (most recent call last):
  File "/data/metab/urbanformvmt/code/inrix_first_run/trip_block_distance_based_features.py", line 52, in <module>
    gdf_buildings_part = import_csv_w_wkt_to_gdf(path_buildings_part, crs)
  File "/data/metab/UFO-MAP/ufo_map/Utils/helpers.py", line 23, in import_csv_w_wkt_to_gdf
    df = pd.read_csv(path)
  File "/home/fewagner/.conda/envs/inrix-env/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/fewagner/.conda/envs/inrix-env/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/fewagner/.conda/envs/inrix-env/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/fewagner/.conda/envs/inrix-env/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/fewagner/.conda/envs/inrix-env/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/home/fewagner/.conda/envs/inrix-env/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/home/fewagner/.conda/envs/inrix-env/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/data/metab/osm/learning-from-urban-form-to-predict-building-heights/Data/2-data_preprocessed/Germany/Berlin/Berlin/Berlin_features/Berlin_part_19_buildings_fts_buildings.csv'
